### ISSUE TITLE
Продукт не умещается в зону отображения

### ISSUE THREAD

**Issue by matuhak** [KotRikD/vk-bugtracker-tickets#2]
1. Заходим в приложение
2. Заходим в продукты > мои
3. Пролистываем до конца

AR: на скриншоте. Игровой продукт не вмещается в область отображения.
ER: корректное отображение.

[Скриншот](https://pp.userapi.com/c831208/v831208085/cdc01/JyLKw-Uu1Rs.jpg)

**Comment by KotRikD** [comment]
Исправлен
