### ISSUE TITLE
Feedback 'Ты пидор'

### ISSUE THREAD

**Issue by KotRikD** [KotRikD/vk-bugtracker-tickets#3]
### Message from BackedDock sent on 2018-04-16 17:42:42 UTC###

> Иди на хуй

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/735086/feedback/2040974](https://rink.hockeyapp.net/manage/apps/735086/feedback/2040974)

**Comment by SevereCloud** [comment]
Подтвердаю
